# karmasoc-feed
FROM node:8.0.0

ARG WORKSPACE=/usr/src/app/karmasoc-feed

# Create app directory
RUN mkdir -p $WORKSPACE
RUN mkdir -p $WORKSPACE/config
RUN mkdir -p $WORKSPACE/logs

COPY ./process.json $WORKSPACE
COPY ./config-kube $WORKSPACE/config
COPY ./karmasoc-feed $WORKSPACE

WORKDIR $WORKSPACE

RUN npm install
RUN npm run build

EXPOSE 9999

CMD ["node","dist/server.js"]