# karmasoc-user
FROM node:7.10.0

ARG WORKSPACE=/usr/src/app/ks-business

# Create app directory
RUN mkdir -p $WORKSPACE
RUN mkdir -p $WORKSPACE/config
RUN mkdir -p $WORKSPACE/logs

COPY ./process.json $WORKSPACE
COPY ./config $WORKSPACE/config
COPY ./ks-business $WORKSPACE

WORKDIR $WORKSPACE

RUN npm install
RUN npm run build
EXPOSE 44006

#CMD node ./dist/index.js

CMD ["node","./dist/src/index.js"]

#CMD pm2 start --no-daemon  process.json --only ks-business --env docker
