# karmasoc-mediaserve
FROM node:8.0.0

ARG WORKSPACE=/usr/src/app/karmasoc-mediaserve

# Create app directory
RUN mkdir -p $WORKSPACE
RUN mkdir -p $WORKSPACE/config
RUN mkdir -p $WORKSPACE/logs

COPY ./process.json $WORKSPACE
COPY ./config $WORKSPACE/config
COPY ./karmasoc-mediaserve $WORKSPACE

WORKDIR $WORKSPACE

RUN npm install pm2 -g
RUN npm install

EXPOSE 8300

CMD node ./index.js
#CMD pm2 start --no-daemon  process.json --only karmasoc-mediaserve --env docker