# karmasoc-user
FROM node:8.0.0

ARG WORKSPACE=/usr/src/app/karmasoc-user

# Create app directory
RUN mkdir -p $WORKSPACE
RUN mkdir -p $WORKSPACE/config
RUN mkdir -p $WORKSPACE/logs

COPY ./process.json $WORKSPACE
COPY ./config-kube $WORKSPACE/config
COPY ./karmasoc-user $WORKSPACE

WORKDIR $WORKSPACE

RUN npm install pm2 -g
RUN npm install --unsafe-perm=true
RUN npm run build

EXPOSE 44001

CMD node ./build/index.js
#CMD pm2 start --no-daemon  process.json --only karmasoc-user --env docker