# Set nginx base image
FROM nginx:latest

# File Author / Maintainer
MAINTAINER Sasikumar Sugumar

RUN mkdir -p /var/www/letsencrypt/.well-known/acme-challenge
RUN mkdir -p /usr/share/nginx/html/.well-known/acme-challenge
RUN mkdir -p /var/www/karmasoc-alpha
RUN mkdir -p /etc/nginx/snippets
RUN mkdir -p /etc/nginx/sites-available
RUN mkdir -p /etc/letsencrypt/live/karmasoc-alpha.com
RUN mkdir -p /etc/nginx/sites-enabled
RUN rm /etc/nginx/conf.d/default.conf
RUN mkdir -p /usr/share/nginx/html/logs	
RUN touch /usr/share/nginx/html/logs/access.log
RUN touch /usr/share/nginx/html/logs/error.log

# Copy custom configuration file from the current directory
COPY ./karmasoc-web/nginx/snippets/letsencrypt.conf /etc/nginx/snippets/letsencrypt.conf
COPY ./karmasoc-web/nginx/snippets/ssl.conf /etc/nginx/snippets/ssl.conf
COPY ./karmasoc-web/nginx/sites-available/karmasoc-alpha.conf  /etc/nginx/conf.d/karmasoc-alpha.conf 
COPY ./karmasoc-web/dist /usr/share/nginx/html

COPY ./karmasoc-web/nginx/letsencrypt/live/karmasoc-alpha.com/fullchain.pem /etc/letsencrypt/live/karmasoc-alpha.com/fullchain.pem
COPY ./karmasoc-web/nginx/letsencrypt/live/karmasoc-alpha.com/privkey.pem /etc/letsencrypt/live/karmasoc-alpha.com/privkey.pem

#RUN  ln -s /etc/nginx/sites-available/karmasoc-alpha.conf /etc/nginx/sites-enabled/karmasoc-alpha.conf

EXPOSE 80