# karmasoc-mediaserve
FROM node:6.8.0

# Create app directory
RUN mkdir -p /usr/src/app/karmasoc-mediaserve
RUN mkdir -p /usr/src/app/karmasoc-mediaserve/config
RUN mkdir -p /usr/src/app/karmasoc-mediaserve/logs

COPY ./process.json /usr/src/app/karmasoc-mediaserve
COPY ./config /usr/src/app/karmasoc-mediaserve/config
COPY ./karmasoc-mediaserve /usr/src/app/karmasoc-mediaserve

WORKDIR /usr/src/app/karmasoc-mediaserve

RUN npm install pm2 -g
RUN npm install
RUN npm run build

EXPOSE 8300

CMD node ./index.js
#CMD pm2 start --no-daemon  process.json --only karmasoc-mediaserve --env docker