sudo: true
group: deprecated-2017Q2

services:  
    - docker

env:  
    global:
        - DOCKER_VERSION=1.11.2-0~trusty
        - DOCKER_COMPOSE_VERSION=1.8.0
        - IMAGE_NAME=karmasoc-feed
        - CLUSTER=karmasoc
        - TASK_DEFINITION=web
        - SERVICE=karmasoc-feed
        - REMOTE_IMAGE_URL=eurosasi/karmasoc-feed
        - DOCKER_FILE=Dockerfile.karmasocfeed

before_install:  

    # list docker-engine versions
    - apt-cache madison docker-engine

    # upgrade docker-engine to specific version
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install --force-yes docker-engine=${DOCKER_VERSION}

    # reinstall docker-compose at specific version
    - sudo rm -f /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
    - git clone https://$GIT_USER:$GIT_KEY@github.com/KarmaSoc/setup.git
    - mv setup/process.json .
    - mv setup/config .
    - mv setup/bin/docker_push.sh .
    - chmod +x docker_push.sh
    - rm -rf setup
before_script:
 
script:  
    - docker build --no-cache=true -f $DOCKER_FILE -t $REMOTE_IMAGE_URL .

after_success:
   # comment
    - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
    - ./docker_push.sh

before_deploy:
  - zip -r karmasoc-feed-archive.zip deploy-dev-start.sh deploy-dev-stop.sh docker-compose-dev.yml appspec.yml || true
  - mkdir -p "karmasoc-feed-deploy"
  - mv karmasoc-feed-archive.zip karmasoc-feed-deploy/karmasoc-feed-archive.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    local_dir: karmasoc-feed-deploy
    bucket: karmasoc-dev-deployment
    region: us-east-1
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      repo: KarmaSoc/karmasoc-feed
      all_branches: false
      branch: graphql
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: karmasoc-dev-deployment
    key: karmasoc-feed-archive.zip
    bundle_type: zip
    application: karmasoc-feed
    deployment_group: karmasoc
    region: us-east-1
    on:
      repo: KarmaSoc/karmasoc-feed
      all_branches: false
      branch: graphql
after_deploy:
  - echo "Performing after deploy procedures......"
notifications:
  email:
    recipients:
      - sasisugumar@gmail.com
  slack: karmasoc:umEs13Hsc8Og49zoSd8mjonk


