# karmasoc-web-server
FROM node:6.8.0

ARG WORKSPACE=/usr/src/app/karmasoc-web-server

# Create app directory
RUN mkdir -p $WORKSPACE
RUN mkdir -p $WORKSPACE/config
RUN mkdir -p $WORKSPACE/logs

COPY ./process.json $WORKSPACE
COPY ./config $WORKSPACE/config

COPY . $WORKSPACE

WORKDIR $WORKSPACE

RUN npm install --unsafe-perm=true

EXPOSE 8200

CMD npm run watch